kind: Namespace
apiVersion: v1
metadata:
  name: front

---
kind: Service
apiVersion: v1
metadata:
  name: front
  namespace: front
  labels:
    app: front
spec:
  selector:
    app: front
  clusterIP: None
  ports:
    - port: 8088
      targetPort: 8088

---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: front
  namespace: front
  labels:
    app: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      name: front
      namespace: front
      labels:
        app: front
    spec:
      containers:
        - name: front
          image: willfuks/pysearchml_front
          ports:
            - containerPort: 8088
          resources:
            requests:
              memory: 256Mi
            limits:
              memory: 512Mi
          env:
            - name: DEBUG_MODE
              value: "1"
