apiVersion: v1
kind: PersistentVolume
metadata:
  name: pysearchml-nfs
  namespace: kubeflow
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: <ClusterIP>
    path: "/"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pysearchml-nfs
  namespace: kubeflow
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
